### ISSUE TITLE
Migrate type tests to TSTyche

### ISSUE THREAD

**Issue by mrazauskas** [FloEdelmann/vue-ts-types#506]
Hey there!

Just wanted to draw your attention that `tsd-lite` got [deprecated](https://github.com/mrazauskas/tsd-lite/issues/364). It is used in your project by the `jest-runner-tsd`.

The architecture of `tsd` was very limited and did not scale well. `jest-runner-tsd` was initially created to test type in Jest repo. I was contributing type tests to the repo for some time. Currently there are around 1200 assertions. At this scale it became painful to debug or add new type features.

You have loads of tests, so the problems should sound familiar. This is why I went on building TSTyche. I have spending two years researching and experimenting. Now it is ready for use. It is made to scale, to be fast and to last for years.

How exactly? For instance, it has testing helpers like `describe()` or `it()` with `.only`, `.skip`, `.todo` run mode modifiers. These are priceless if you want to focus on one feature.

It ships with `expect` style assertions that can be passed an expression or a type on both side. This means that types can be compared directly without creating intermediate values. The run mode modifiers can be used directly on assertions like `expect.fail`, `expect.only` or `expect.skip`.

TSTyche has a lot to offer. It is fast and lightweight (zero dependencies, install size below 200kB).

Currently TSTyche is used by Immutable.js, Jest, Redwood and few more smaller project (including my own packages).

Repo: https://github.com/tstyche/tstyche
Documentation: https://tstyche.org

---

Would you be interested to migrate to TSTyche? This shouldn’t be hard, because you already structured files using `describe()`.

I am happy to help setting up TSTyche and updating test files. Just wanted to ask before opening a PR.

**Comment by FloEdelmann** [comment]
Thanks for letting me know and thanks for the PR! TSTyche looks very well made! :slightly_smiling_face: 

Would you fancy completing the migration from `jest-runner-tsd` and `@tsd/typescript` to TSTyche in the PR?

**Comment by mrazauskas** [comment]
Thanks for quick response. Glad to hear you like TSTyche.

Yes, I will rework and push all remaining tests soon.

**Comment by mrazauskas** [comment]
One more detail to mention: at the moment TSTyche does not have watch mode. It was simply too much for v1. I will definitely add it at some point, watch mode is on high priority feature list. Hope that’s not a blocker for you.

**Comment by FloEdelmann** [comment]
As the project is not that big, lack of the watch mode is fine for now. I'll be happy to test it when you implement it though :)
