### ISSUE TITLE
export 'objectProp' (imported as 'objectProp') was not found in 'vue-ts-types' (module has no exports)

### ISSUE THREAD

**Issue by andrew-webster** [FloEdelmann/vue-ts-types#706]
This error has appeared after a deployment was made. Looks like something in the last release today may have caused this to fail. Falling back to 1.6.1 fixed the issue for me.

**Comment by edgarsbergs** [comment]
Same here. 1.6.2. also works.

**Comment by FloEdelmann** [comment]
Thanks for letting me know. I've mistakenly switched from CommonJS to ESM in a minor version. I switched back to CommonJS in #707 and released https://github.com/FloEdelmann/vue-ts-types/releases/tag/v1.7.1 containing this fix. Please let me know if it works for you!
